version: '3'
services:
  deepscholar.front:
    image: nginx
    volumes:
      - ./front/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - deepscholar.client
      - deepscholar.server
    ports:
      - "${DS_FRONT_PORT}:80"
  deepscholar.client:
    volumes:
      - ./client:/root/client
      - /root/client/node_modules/
    image: node:8.1.2
    working_dir: /root/client
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - deepscholar.server
    ports:
      - "${DS_CLIENT_PORT}:3000"
    command: bash -c 'npm i && npm start'
  deepscholar.server:
    volumes:
      - ./server:/root/server
      - /root/server/node_modules/
    image: node:8.1.2
    working_dir: /root/server
    environment:
      - NODE_ENV=development
      - DEEP_SCHOLAR_URL=${DEEP_SCHOLAR_URL}
      - DEEP_SCHOLAR_TOKEN_SECRET=${DEEP_SCHOLAR_TOKEN_SECRET}
      - DEEP_SCHOLAR_TOKEN_ISSUER=${DEEP_SCHOLAR_TOKEN_ISSUER}
      - DEEP_SCHOLAR_TOKEN_AUDIENCE=${DEEP_SCHOLAR_TOKEN_AUDIENCE}
      - DS_SERVER_PORT=${DS_SERVER_PORT}
      - DS_BULK_LIMIT_BYTE_PER_REQUEST=${DS_BULK_LIMIT_BYTE_PER_REQUEST}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - MONGODB_APPLICATION_DATABASE=${MONGODB_APPLICATION_DATABASE}
      - MONGODB_APPLICATION_USER=${MONGODB_APPLICATION_USER}
      - MONGODB_APPLICATION_PASS=${MONGODB_APPLICATION_PASS}
    depends_on:
      - deepscholar.elasticsearch
      - deepscholar.database
    ports:
      - "${DS_SERVER_PORT}:3001"
    command: bash -c "npm i && npm start"
  deepscholar.database:
    volumes:
      - dbdata:/data/db
    image: aashreys/mongo-auth
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=${MONGODB_ADMIN_USER}
      - MONGODB_ADMIN_PASS=${MONGODB_ADMIN_PASS}
      - MONGODB_APPLICATION_DATABASE=${MONGODB_APPLICATION_DATABASE}
      - MONGODB_APPLICATION_USER=${MONGODB_APPLICATION_USER}
      - MONGODB_APPLICATION_PASS=${MONGODB_APPLICATION_PASS}
    ports:
      - "${DS_DB_PORT}:27017"
  deepscholar.mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ADMIN_PASS}
      - ME_CONFIG_MONGODB_SERVER=deepscholar.database
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - deepscholar.database
    ports:
      - "${DS_ME_PORT}:8081"
  deepscholar.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${DS_ES_PORT}:9200"
  deepscholar.kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    environment:
      - ELASTICSEARCH_URL=http://deepscholar.elasticsearch:9200
    depends_on:
      - deepscholar.elasticsearch
    ports:
      - "${DS_KIBANA_PORT}:5601"
  deepscholar.elasticsearch-head:
    image: mobz/elasticsearch-head:5
    depends_on:
      - deepscholar.elasticsearch
    ports:
      - "${DS_ESHEAD_PORT}:9100"
volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
